development:
  host: localhost
  database: inn_maps_development

test:
  host: localhost
  database: inn_maps_test

# set these environment variables on your prod server
<% if ENV['MONGOHQ_URL'] %>
  production:
    sessions:
      default:
        uri: <%= ENV['MONGOHQ_URL'] %>
        options:
          skip_version_check: true
          safe: true
<% end %>